---
title: "data import"
author: "Ziang Niu"
date: "2025-09-16"
output: html_document
---

```{r}
library(tidyverse)
library(readxl)
library(haven)
```

import a dataset.

```{r}
litters_df =
  read_csv("data/FAS_litters.csv")
```

look at your data!

```{r}
names(litters_df)
```

Update the names in `litters_df`.

```{r}
litters_df =
  janitor::clean_names(litters_df)
```

look at data!
```{r}
litters_df
```

Sometimes skimming data is neat?

```{r}
skimr::skim(litters_df)
```

## Fix the missingness

```{r}
litters_df =
  read_csv("data/FAS_litters.csv", na = c("NA", ".", ""), skip = 1)
```

## Import pups data

```{r}
pups_df =
  read_csv(
    "data/FAS_pups.csv",
    skip = 3,
    na = c("NA", ".", "")
  )

pups_df =
  janitor::clean_names(pups_df)
```

## Okay what about excel

CSVs are really great but sometimes we have excel.

```{r}
mlb_df =
  read_excel("data/mlb11.xlsx")
```

Import LotR word counts.

```{r}
fatr_df =
  read_excel("data/LotR_Words.xlsx")
```


















